"""Write a TSUBAME job script from a command, and optionally submit it.

The 125 scripts under ``archive/`` are 20 lines of identical boilerplate around
one or two real commands. This generates that boilerplate so a new job is the
command plus its resources, and so the prologue cannot drift back into the form
that silently kills jobs (see ``lib.sh``).

    python jobs/submit.py --name lm_pre --resource node_f --hours 8 -- \
        pipelines/train/clm.py --token-dir data/lm_tokens_allatom

Writes ``jobs/generated/<name>.sh`` and prints the qsub command. It does NOT
submit unless ``--submit`` is passed: what a job does, where it runs and how
long it takes should be stated and agreed before it enters the queue.
"""

from __future__ import annotations

import argparse
import os
import shlex
import subprocess
import sys
from pathlib import Path

JOBS_DIR = Path(__file__).resolve().parent
REPO_ROOT = JOBS_DIR.parent
GENERATED = JOBS_DIR / "generated"

#: TSUBAME resource types, with the billing coefficient per node-hour so the
#: printed estimate is honest about cost rather than only about walltime.
RESOURCES: dict[str, float] = {
    "node_f": 1.0,  # full node: 4x H100, 192 cores
    "node_h": 0.5,
    "node_q": 0.25,  # 1 GPU, 48 cores
    "node_o": 0.125,
    "gpu_1": 0.25,  # 1 full H100
    "cpu_4": 0.0225,
    "cpu_8": 0.045,
    "cpu_16": 0.09,
    "cpu_40": 0.225,
    "cpu_80": 0.45,
    "cpu_160": 0.9,
}

_TEMPLATE = """#!/bin/sh
#$ -cwd
#$ -l {resource}=1
#$ -l h_rt={hours}:00:00
#$ -N {name}
{array}
# {description}
#
# Generated by jobs/submit.py. Edit and re-run that rather than this file.

. "{lib}"

{env}{commands}
"""


def build(  # noqa: PLR0913
    name: str,
    resource: str,
    hours: int,
    commands: list[list[str]],
    description: str,
    array: str | None = None,
    env: dict[str, str] | None = None,
) -> str:
    """Render a job script. ``commands`` are argv lists run through ``$PY``."""
    if resource not in RESOURCES:
        known = ", ".join(sorted(RESOURCES))
        msg = f"unknown resource {resource!r}; known: {known}"
        raise ValueError(msg)
    body = "\n".join(
        '"$PY" ' + " ".join(shlex.quote(a) for a in cmd) for cmd in commands
    )
    env_lines = "".join(
        f"export {k}={shlex.quote(v)}\n" for k, v in (env or {}).items()
    )
    return _TEMPLATE.format(
        resource=resource,
        hours=hours,
        name=name,
        array=f"#$ -t {array}\n" if array else "",
        description=description,
        lib='$(dirname "$0")/../lib.sh',
        env=env_lines + ("\n" if env_lines else ""),
        commands=body,
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--name", required=True, help="SGE job name (-N)")
    parser.add_argument(
        "--resource", required=True, choices=sorted(RESOURCES), help="resource type"
    )
    parser.add_argument("--hours", type=int, required=True, help="walltime cap")
    parser.add_argument(
        "--description",
        default="",
        help="one line on what this job does; ends up in the script header",
    )
    parser.add_argument("--array", default=None, help="array spec, e.g. 1-10")
    parser.add_argument(
        "--env",
        action="append",
        default=[],
        metavar="K=V",
        help="extra environment variable (repeatable)",
    )
    parser.add_argument(
        "--group",
        default=os.environ.get("PROLIT_QSUB_GROUP", ""),
        help="billing group for qsub -g (default: $PROLIT_QSUB_GROUP)",
    )
    parser.add_argument(
        "--submit",
        action="store_true",
        help="actually qsub. Off by default: agree the job first.",
    )
    parser.add_argument(
        "command",
        nargs=argparse.REMAINDER,
        help="entry point and its flags, after a bare --",
    )
    args = parser.parse_args()

    cmd = args.command[1:] if args.command[:1] == ["--"] else args.command
    if not cmd:
        parser.error("no command given; put it after a bare --")

    env = {}
    for item in args.env:
        key, _, value = item.partition("=")
        if not value:
            parser.error(f"--env expects K=V, got {item!r}")
        env[key] = value

    # The submitter cannot know the run directory -- without --run-name it is
    # the W&B run id, decided at startup -- so it passes what it knows through
    # the environment and the run folds it into its own run.json.
    env = {
        "PROLIT_JOB_NAME": args.name,
        "PROLIT_JOB_RESOURCE": args.resource,
        "PROLIT_JOB_HOURS": str(args.hours),
        **env,
    }
    script = build(
        name=args.name,
        resource=args.resource,
        hours=args.hours,
        commands=[cmd],
        description=args.description or f"{cmd[0]} on {args.resource}",
        array=args.array,
        env=env,
    )
    GENERATED.mkdir(exist_ok=True)
    path = GENERATED / f"{args.name}.sh"
    path.write_text(script)
    path.chmod(0o755)

    cost = RESOURCES[args.resource] * args.hours
    rel = path.relative_to(REPO_ROOT)
    print(f"wrote {rel}")
    print(
        f"  {args.resource} for up to {args.hours} h "
        f"-> at most {cost:.2f} node-hours of billing"
    )
    qsub = ["qsub", *(["-g", args.group] if args.group else []), str(rel)]
    print("  " + " ".join(qsub))

    if args.submit:
        subprocess.run(qsub, check=True, cwd=REPO_ROOT)  # noqa: S603
    else:
        print("  (not submitted; pass --submit)")


if __name__ == "__main__":
    sys.exit(main())
